### PR TITLE
Aceblock did resolver data added

### PR DESCRIPTION
**Pull request by aceblockID**

### CODE REVIEW

**Comment by azuzi** [comment]
HI @aceblockID ,

During the testing, the docker image of the ace-block driver didn't start (or the port didn't respond). 
Also could you please follow the port sequence number as per the order and could you change it to 8111.

**Comment by aceblockID** [comment]
Hi, @azuzi , 

requested changes has been made. Please test and comment.

**Comment by azuzi** [comment]
Hi @aceblockID ,

We have tested the driver for aceBlock DID. But uni resolver couldn't resolve the DID documents. I have attached the screenshots of log.
Screenshot from 2020-10-22 10-12-26
Screenshot from 2020-10-22 10-12-11

**Comment by BernhardFuchs** [comment]
We could solve the problem with not matching patterns from above.

Now there seems to be a problem with the port mapping and the request handling of the driver.
In the docker-compose file the port mapping is `8111:8111`, which means the container is listening on port 8111 (the second port number).
When I start it, the logs say it's started on port 8080 and the request never receives the driver.
```
> did-resolver@1.0.0 start /usr/src/app
> node ./did-resolver.js

20Y-11-06 12:09:47 info: Did resolver API server started on: 8080
Did resolver API server started on: 8080
```

If I change the mapping to `8111:8080` the resolver is forwarding the request but the driver throws following errors:
```
20Y-11-06 12:09:50 info: GET /
20Y-11-06 12:09:50 info: Error 400: Invalid service 'GET /'
20Y-11-06 12:09:50 info: GET /
20Y-11-06 12:09:50 info: Error 400: Invalid service 'GET /'
20Y-11-06 12:09:51 info: GET /
20Y-11-06 12:09:51 info: Error 400: Invalid service 'GET /'
20Y-11-06 12:09:51 info: GET /
20Y-11-06 12:09:51 info: Error 400: Invalid service 'GET /'
20Y-11-06 12:09:51 info: GET /
20Y-11-06 12:09:51 info: Error 400: Invalid service 'GET /'
20Y-11-06 12:09:51 info: GET /
20Y-11-06 12:09:51 info: Error 400: Invalid service 'GET /'
...
```

**Pull request merged**
