### PR TITLE
chore: update orb driver to v1.0.0-rc4-snapshot-7125f6a

### PR DESCRIPTION
**Pull request by fqutishat**
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>

### CODE REVIEW

**Comment by fqutishat** [comment]
@BernhardFuchs can you review

**Review by bstasyszyn — APPROVED** [review]

**Comment by BernhardFuchs** [comment]
After deployment the driver fails with following error on startup:
```
2022/08/31 15:24:08 Failed to run rp: Neither verify-resolution-result-type (command line flag) nor ORB_DRIVER_VERIFY_RESOLUTION_RESULT_TYPE (environment variable) have been set.
```

**Comment by fqutishat** [comment]
> After deployment the driver fails with following error on startup:
> 
> ```
> 2022/08/31 15:24:08 Failed to run rp: Neither verify-resolution-result-type (command line flag) nor ORB_DRIVER_VERIFY_RESOLUTION_RESULT_TYPE (environment variable) have been set.
> ```

@BernhardFuchs I already sit it here https://github.com/decentralized-identity/universal-resolver/pull/317/files#diff-e9cbb0224c4a3d23a6019ba557e0cd568c1ad5e1582ff1e335fb7d99b7a1055dR43 Is there other place to set the env var?

**Comment by fqutishat** [comment]
@BernhardFuchs Also I run docker compose locally without issue 

`orb-did-driver      |  [httpserver] 2022/08/31 18:06:43 UTC - httpserver.New -> INFO Registering handler for [/1.0/identifiers/{id}]
orb-did-driver      |  [orb-driver] 2022/08/31 18:06:43 UTC - startcmd.(*HTTPServer).Start -> INFO started orb driver service
orb-did-driver      |  [httpserver] 2022/08/31 18:06:43 UTC - httpserver.(*Server).Start.func1 -> INFO listening for requests on [0.0.0.0:8121]`

**Comment by fqutishat** [comment]
@BernhardFuchs any updates

**Comment by peacekeeper** [comment]
@fqutishat Just a quick note that @BernhardFuchs is offline this week, he should be able to review this again next week.

**Comment by BernhardFuchs** [comment]
Sorry for the delay, I was on vacation last week.  

Most driver contributors add default values to their image. The [.env](https://github.com/decentralized-identity/universal-resolver/blob/main/.env) is only used for docker-compose and not picked-up by our CI/CD pipeline. Maybe we improve that in future.  

For now we have a custom [config file](https://github.com/decentralized-identity/universal-resolver/blob/main/ci/deploy-k8s-aws/scripts/driver-config.yaml) where we add the env variables. I just added the missing env on this [branch](https://github.com/decentralized-identity/universal-resolver/blob/f8bc2503fcd9450291a4926806e09cd71a975c42/ci/deploy-k8s-aws/scripts/driver-config.yaml#L14) and that solves the problem at startup.  

But when resolving the example did, the resolver throws following error:
```
[internalError] Driver cannot retrieve result for did:orb:hl:uEiBuxTFn4L_Hn8KsOWo8e9kqWP38MThBaToB_5yV3c5QTg:uoQ-BeEJpcGZzOi8vYmFma3JlaWRveXV5d3B5Zjd5NnA0Zmxiem5pNmh4d2prbGQ2N3ltanlpZnV0dWFwN3RzazUzdHNxank:EiD_igS1OSEftg5BGfisJGOS1rgcx5AkQhX0h1B4dHTUYA: 400 Bad Request (failed to resolve did: failed to get endpoints: get anchor origin for [did:orb:hl:uEiBuxTFn4L_Hn8KsOWo8e9kqWP38MThBaToB_5yV3c5QTg:uoQ-BeEJpcGZzOi8vYmFma3JlaWRveXV5d3B5Zjd5NnA0Zmxiem5pNmh4d2prbGQ2N3ltanlpZnV0dWFwN3RzazUzdHNxank:EiD_igS1OSEftg5BGfisJGOS1rgcx5AkQhX0h1B4dHTUYA]: unable to read anchor[hl:uEiBuxTFn4L_Hn8KsOWo8e9kqWP38MThBaToB_5yV3c5QTg:uoQ-BeEJpcGZzOi8vYmFma3JlaWRveXV5d3B5Zjd5NnA0Zmxiem5pNmh4d2prbGQ2N3ltanlpZnV0dWFwN3RzazUzdHNxank] from CAS: failed to send request: Get "https://ipfs.io/ipfs/bafkreidoyuywpyf7y6p4flbzni6hxwjkld67ymjyifutuap7tsk53tsqjy": context deadline exceeded (Client.Timeout exceeded while awaiting headers))
```

There are no logs releated to the request from the driver itself.

**Comment by fqutishat** [comment]
@BernhardFuchs it's fixed. can you try

**Pull request merged**
