### PR TITLE
support polygonid did method

### PR DESCRIPTION
**Pull request by ilya-korotya**
I have included a docker image to address the PolygonID DID method. You can find some tests related to this in the associated PR.

**PolygonID DID specification:** https://github.com/0xPolygonID/did-polygonid/blob/main/did-polygonid-method-draft.md#method-specific-identifier
**PolygonID DID resolver specification:** https://github.com/0xPolygonID/did-polygonid/blob/main/did-polygonid-method-draft.md#resolve

Tested on:
1. **OS**: Fedora; **CPU**: i7-7600U

Contact information:
1. id@polygon.technology
2. https://github.com/ilya-korotya
3. https://github.com/demonsh

### CODE REVIEW

**Comment by ilya-korotya** [comment]
@peacekeeperjust want to make sure you know about this PR since I can't set Reviewers.

**Comment by BernhardFuchs** [comment]
Just tested it and the two example DIDs with the query string don't work.  
I'm also not sure what the purpose of the query string is.

**Comment by ilya-korotya** [comment]
@BernhardFuchs Hi. We use query string to expand options for requests. This gives us the ability to request a historical DID document. I'm going to check these errors. Thanks for reviewing!

**Comment by BernhardFuchs** [comment]
@ilya-korotya Apparently there is some implementation missing on our side. @peacekeeper will implement these in the future and get back to you.  

We can merge the PR in the meanwhile as the basic functionality is there.

**Comment by ilya-korotya** [comment]
@BernhardFuchs Should I remove examples that don't work?

**Comment by peacekeeper** [comment]
> @BernhardFuchs Should I remove examples that don't work?

@ilya-korotya Yes if it's okay with you, I'd propose to remove those examples for now, and we'll add them back in once the Universal Resolver properly supports the query variables.

**Comment by BernhardFuchs** [comment]
Thx for the investigation. It's the same behaviour for me when calling the API at https://dev.uniresolver.io  

One problem, like you mentioned, is that it only works with encoded `:` and another, that the frontend returns an error for DIDs with a query parameter (maybe the same root cause). We still have to implement some pieces on our part here.  

The `testIdentifiers` in the `application.yml` are used to populate the frontend and also for the nightly runs against [DID Lint](https://didlint.ownyourdata.eu/), which in turn is responsible for the DID conformance colors at the [website](https://dev.uniresolver.io/).  

For now it's best to remove the example DIDs with the query parameter. You can still use the functionality at the API level with the hack of encoding the `:`.

**Pull request merged**
