### PR TITLE
Add did:io driver.

### PR DESCRIPTION
**Pull request by lzxm160**
With this PR I would like to add the IoTex DID driver support to the universal resolver

Driver Github: https://github.com/iotexproject/uni-resolver-driver-did-io

### CODE REVIEW

**Comment by lzxm160** [comment]
@peacekeeper  Could you pls help review this pr

**Comment by yutongp** [comment]
@philpotisk @peacekeeper, it could be very nice if you guys could take some time to review on our chain's integration. Thank you very much. Appreciated.

**Comment by azuzi** [comment]
@yutongp  Hi, 
I have reviewed the PR, But I've encountered an issue.
The issue is the driver is responding but the resolver returns a null document (When calling the Uni-Resolver directly).
Also I cant read any log files, so how to activate or read the log file?
Screenshot from 2020-06-24 14-37-19

**Comment by yutongp** [comment]
thank you @azuzi. we are working on resolve the problem. But now we kind of blocked by #111.

**Comment by yutongp** [comment]
Hi @azuzi, the issue should be fixed.
Screen Shot 2020-06-26 at 2 50 47 PM

I used to have similar issue, because I was not using the uni-resolver-web image I built locally, so our driver was not included.
Appreciate if you can review the PR again.

One more thing, I don't know how to fix the CI build. I was able to download that maven package by setting github token in `resolver/java/settings.xml`, but I am not sure CI should handle this.

**Comment by bjwswang** [comment]
@azuzi @yutongp  same issue in PR https://github.com/decentralized-identity/universal-resolver/pull/112
Aftet github token added in to `settings.xml`,I can successully resolve did with universal resolve web in my test environment now. But CI still not working . Seems CI should also manage the build with available git token.

**Comment by yutongp** [comment]
Hi @azuzi @BernhardFuchs @peacekeeper,

Now we are able to pass the CI on our fork: https://github.com/lzxm160/universal-resolver/pull/5. Please help us review the pr again when you have time. Thank you.

**Comment by BernhardFuchs** [comment]
#114 

Issue with CI pipeline is explained there

**Comment by thomas-tran** [comment]
> Hi @azuzi, the issue should be fixed.
> Screen Shot 2020-06-26 at 2 50 47 PM
> 
> I used to have similar issue, because I was not using the uni-resolver-web image I built locally, so our driver was not included.
> Appreciate if you can review the PR again.
> 
> One more thing, I don't know how to fix the CI build. I was able to download that maven package by setting github token in `resolver/java/settings.xml`, but I am not sure CI should handle this. #114

How did you fix this issue?

**Comment by yutongp** [comment]
> > Hi @azuzi, the issue should be fixed.
> > Screen Shot 2020-06-26 at 2 50 47 PM
> > I used to have similar issue, because I was not using the uni-resolver-web image I built locally, so our driver was not included.
> > Appreciate if you can review the PR again.
> > One more thing, I don't know how to fix the CI build. I was able to download that maven package by setting github token in `resolver/java/settings.xml`, but I am not sure CI should handle this. #114
> 
> How did you fix this issue?

Yes. As I said in the first line, it is fixed.

**Comment by lzxm160** [comment]
The ci is fixed,but I doesn't have write access,pls help merge this@azuzi @BernhardFuchs @peacekeeper

**Comment by lzxm160** [comment]
Please help us review the pr again @BernhardFuchs

**Pull request merged**
