### PR TITLE
Bump did:iden3 driver to v0.0.4

### PR DESCRIPTION
**Pull request by volodymyr-basiuk**
- added EcdsaSecp256k1RecoveryMethod2020 verification method for ETH based identities
- use iden3 driver image for polygonid did (due to the same codebase)
- update spec links

### CODE REVIEW

**Comment by ilya-korotya** [comment]
@BernhardFuchs LGTM

**Comment by BernhardFuchs** [comment]
Sorry for the late response.   
I tested it now but the driver throws following error:
```
2024/07/21 09:46:30 HTTP server start on '0.0.0.0:8080'
2024/07/21 10:04:39 failed get did document: network is not supported
github.com/iden3/driver-did-iden3/pkg/services.init
	/build/pkg/services/registry.go:15
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6230
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6207
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6207
runtime.main
	/usr/local/go/src/runtime/proc.go:233
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571
```
I'm using the example DID on dev.uniresolver.io `did:iden3:polygon:amoy:xC8VZLUUfo5p9DWUawReh7QSstmYN6zR7qsQhQCsw`

**Comment by volodymyr-basiuk** [comment]
> Sorry for the late response. I tested it now but the driver throws following error:
> 
> ```
> 2024/07/21 09:46:30 HTTP server start on '0.0.0.0:8080'
> 2024/07/21 10:04:39 failed get did document: network is not supported
> github.com/iden3/driver-did-iden3/pkg/services.init
> 	/build/pkg/services/registry.go:15
> runtime.doInit
> 	/usr/local/go/src/runtime/proc.go:6230
> runtime.doInit
> 	/usr/local/go/src/runtime/proc.go:6207
> runtime.doInit
> 	/usr/local/go/src/runtime/proc.go:6207
> runtime.main
> 	/usr/local/go/src/runtime/proc.go:233
> runtime.goexit
> 	/usr/local/go/src/runtime/asm_amd64.s:1571
> ```
> 
> I'm using the example DID on dev.uniresolver.io `did:iden3:polygon:amoy:xC8VZLUUfo5p9DWUawReh7QSstmYN6zR7qsQhQCsw`

Sorry for that issue, it's fixed now,
could you please try again ?

**Comment by BernhardFuchs** [comment]
Thx for the quick fix.  
Looks good now

**Pull request merged**
