### PR TITLE
Add did:vaa resolver

### PR DESCRIPTION
**Pull request by caict-develop-zhangbo**

### CODE REVIEW

**Comment by caict-develop-zhangbo** [comment]
Request to add the vaa did driver to the Universal Resolver.

The DID Method spec: https://github.com/caict-develop-zhangbo/vaa-method

The DID Driver Implementation: https://github.com/caict-develop-zhangbo/uni-resolver-driver-did-vaa

The DID Driver Image: https://hub.docker.com/repository/docker/caictdevelop/driver-did-vaa

The PR to add the vaa DID method to the DID Method Registry is already merged: https://w3c.github.io/did-spec-registries/#did-methods

**Comment by BernhardFuchs** [comment]
The driver fails with following error log:
```
15:35:59,990 -  WARN [uniresolver.driver.servlet.ResolveServlet] - Driver reported for did:vaa:3wJVWDQWtDFx27FqvSqyo5xsTsxC: docuement not exist
uniresolver.ResolutionException: docuement not exist
	at uniresolver.driver.did.vaa.DidVaaDriver.resolve(DidVaaDriver.java:80)
	at uniresolver.driver.servlet.ResolveServlet.doGet(ResolveServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

Pls also follow the port sequence, which would mean `8115:8080` atm.

I can take care of the merge conflicts.

**Comment by caict-develop-zhangbo** [comment]
Sorry for  this error, we have fixed it. Please check it again. Thank you very much.

**Comment by caict-develop-zhangbo** [comment]
@BernhardFuchs  Thank you very much. I'd like to know when did:vaa can appear in https://dev.uniresolver.io/ supported methods list?

**Comment by BernhardFuchs** [comment]
I've just added it to the supported and to the examples list in the UI component.

**Pull request merged**
