### PR TITLE
Add ONT ID driver

### PR DESCRIPTION
**Pull request by AlverLyu**
Request to add the ONT ID Driver to the universal resolver.

The DID method spec can be found here https://github.com/ontio/ontology-DID/blob/master/docs/en/DID-ONT-method.md.

ONT ID has also been added to the DID Method Registry: https://w3c-ccg.github.io/did-method-registry/#the-registry.

### CODE REVIEW

**Comment by AlverLyu** [comment]
@peacekeeper  Could you please kindly review it?

**Comment by peacekeeper** [comment]
@AlverLyu sorry for taking so long. I made one small change to the docker-compose service name, but other than that it works fine! Thank you very much for the contribution.

**Comment by AlverLyu** [comment]
@peacekeeper Thank you.

Is this going to be added to https://uniresolver.io/ ?

**Comment by peacekeeper** [comment]
@AlverLyu it has been deployed now, sorry again for taking a while, and thanks for the contribution!

**Pull request merged**
