### PR TITLE
did:iota driver implementation

### PR DESCRIPTION
**Pull request by UMR1352**
Adds a driver capable of resolving DID Documents on the IOTA network (iota mainnet, shimmer, or any custom network).

### CODE REVIEW

**Comment by BernhardFuchs** [comment]
We did a test deployment of the driver to dev.uniresolver.io and it crashes on startup with following logs:
```
./uni-resolver-driver-iota: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./uni-resolver-driver-iota)
./uni-resolver-driver-iota: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./uni-resolver-driver-iota)
./uni-resolver-driver-iota: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./uni-resolver-driver-iota)
```

**Comment by UMR1352** [comment]
@BernhardFuchs sorry for the issue, could you please try again now?

**Comment by BernhardFuchs** [comment]
Just tried it again and the driver is throwing a different error now:
```
2024-05-17T07:46:11.006657Z ERROR uni_resolver_driver_iota: error=(500, "did resolution failed: the attached handler failed")
```

**Comment by UMR1352** [comment]
@BernhardFuchs I should have fixed the issue, could you please take a look?

**Comment by BernhardFuchs** [comment]
Great this works now.  
I had to adjust the custom build pipeline. That's why I merged it with this PR https://github.com/decentralized-identity/universal-resolver/pull/425

**Pull request closed without merging**
