### PR TITLE
Add a Blockstack driver

### PR DESCRIPTION
**Pull request by jcnelson**
This PR adds support for handling DIDs that start with `did:bsk`.  Apologies in advance if I broke a convention or two in this PR; I am not very familiar with maven.

The DID format is as follows:

```
    did:bsk:v0:${B58CHECK_ADDRESS}-${NAME_INDEX}
```

where `${B58CHECK_ADDRESS}` is a base58-encoded public key hash (i.e. a Bitcoin address) and `${NAME_INDEX}` is the nth time this address has been used as an identifier.

Resolution works as follows:

1. Resolve `${B58CHECK_ADDRESS}` to the time-ordered list of Blockstack IDs that have pointed to it
2. Select the name at the `${NAME_INDEX}` index
3. Resolve the name to a JWT signed by the public key whose address is `${B58CHECK_ADDRESS}`
4. Return the public key from the JWT to the resolver.

The driver by default directs its queries to `https://core.blockstack.org`, whose source code is available [here](https://github.com/blockstack/blockstack-core/tree/master/api).

**Notes on testing**

Tomorrow, we will be patching `core.blockstack.org` to include the requisite public key responses in its queries.  If you try this today, DID lookups will fail for want of a public key.

All comments welcome.

### CODE REVIEW

**Comment by csuwildcat** [comment]
Are you eventually going to add node support into this image? In the long run, that may be better, so the UR can resolve without relying on an external domain.

**Comment by jcnelson** [comment]
@csuwildcat yes, that's the plan.  I didn't see any of the other drivers' Dockerfiles attempt to install full nodes of their own, so I thought having this driver call out to an external service would be acceptable for the time being.

**Comment by jcnelson** [comment]
Updated the PR: all instances of `bsk` are replaced with `stack`.  The format of Blockstack's DID is `did:stack:v0:${address}-${name_index}`

**Comment by jcnelson** [comment]
Can I go ahead and merge this?

**Pull request merged**
