### PR TITLE
new driver for non-default location behaviour

### PR DESCRIPTION
**Pull request by fabianekc**

### CODE REVIEW

**Comment by BernhardFuchs** [comment]
Following error is thrown for one of the example did:
```
[invalidDid] Cannot parse DID: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@https://did2.data-container.net
```

Pls also solve merge conflicts

**Comment by fabianekc** [comment]
this is strange - it works against the OYDID resolver:    
`curl https://oydid-resolver.data-container.net/1.0/identifiers/did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@https://did2.data-container.net`

then I tried it successfully with the %-encoded @ sign (since @ does maybe not conform to DID-Core ABNF definition):    
`curl https://oydid-resolver.data-container.net/1.0/identifiers/did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk%40https://did2.data-container.net`

here is the log output from running unireslover locally:
```
universal-resolver-uni-resolver-web-1  | [qtp1310540333-16] DEBUG servlet.ResolveServlet (doGet) - Incoming resolve request: /1.0/identifiers/did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk%40https://did2.data-container.net
universal-resolver-uni-resolver-web-1  | [qtp1310540333-16] INFO servlet.ResolveServlet (doGet) - Incoming DID string: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@https://did2.data-container.net
universal-resolver-uni-resolver-web-1  | [qtp1310540333-16] INFO servlet.ResolveServlet (doGet) - Incoming Accept: header string: */*
universal-resolver-uni-resolver-web-1  | [qtp1310540333-16] DEBUG servlet.ResolveServlet (doGet) - Using resolution options: {accept=application/did+ld+json}
universal-resolver-uni-resolver-web-1  | [qtp1310540333-16] DEBUG local.LocalUniResolver (resolveRepresentation) - resolveRepresentation(did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@https://did2.data-container.net)  with options: {accept=application/did+ld+json}
universal-resolver-uni-resolver-web-1  | [qtp1310540333-16] WARN local.LocalUniResolver (resolveOrResolveRepresentation) - Cannot parse DID: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@https://did2.data-container.net
universal-resolver-uni-resolver-web-1  | [qtp1310540333-16] WARN servlet.ResolveServlet (doGet) - Resolve problem for did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@https://did2.data-container.net: Cannot parse DID: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@https://did2.data-container.net
universal-resolver-uni-resolver-web-1  | uniresolver.ResolutionException: Cannot parse DID: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@https://did2.data-container.net
universal-resolver-uni-resolver-web-1  | 	at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentation(LocalUniResolver.java:92)
universal-resolver-uni-resolver-web-1  | 	at uniresolver.local.LocalUniResolver.resolveRepresentation(LocalUniResolver.java:64)
```

Could it be that the `@` is causing problems within Uniresolver?

**Comment by peacekeeper** [comment]
@fabianekc the characters `@`, `:`, `/` are all invalid as part of a DID's method-specific identifier.

You should fix the example DIDs to conform to DID syntax: https://www.w3.org/TR/did-core/#did-syntax

**Comment by fabianekc** [comment]
@peacekeeper yes - I agree that `@` is invalid but I understand that the ABNF allows %-escaping; and `did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk%40https://did2.data-container.net` is still not working on my local uniresolver setup?!

any hints?

**Comment by fabianekc** [comment]
I have now %-encoded `@`,`:`,`/` and still get the error:

```
universal-resolver-uni-resolver-web-1  | [qtp1310540333-15] DEBUG servlet.ResolveServlet (doGet) - Incoming resolve request: /1.0/identifiers/did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk%40httpshttps%3A%2F%2Fdid2.data-container.net
universal-resolver-uni-resolver-web-1  | [qtp1310540333-15] INFO servlet.ResolveServlet (doGet) - Incoming DID string: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@httpshttps://did2.data-container.net
universal-resolver-uni-resolver-web-1  | [qtp1310540333-15] INFO servlet.ResolveServlet (doGet) - Incoming Accept: header string: */*
universal-resolver-uni-resolver-web-1  | [qtp1310540333-15] DEBUG servlet.ResolveServlet (doGet) - Using resolution options: {accept=application/did+ld+json}
universal-resolver-uni-resolver-web-1  | [qtp1310540333-15] DEBUG local.LocalUniResolver (resolveRepresentation) - resolveRepresentation(did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@httpshttps://did2.data-container.net)  with options: {accept=application/did+ld+json}
universal-resolver-uni-resolver-web-1  | [qtp1310540333-15] WARN local.LocalUniResolver (resolveOrResolveRepresentation) - Cannot parse DID: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@httpshttps://did2.data-container.net
universal-resolver-uni-resolver-web-1  | [qtp1310540333-15] WARN servlet.ResolveServlet (doGet) - Resolve problem for did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@httpshttps://did2.data-container.net: Cannot parse DID: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@httpshttps://did2.data-container.net
universal-resolver-uni-resolver-web-1  | uniresolver.ResolutionException: Cannot parse DID: did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk@httpshttps://did2.data-container.net
universal-resolver-uni-resolver-web-1  | 	at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentation(LocalUniResolver.java:92)
universal-resolver-uni-resolver-web-1  | 	at uniresolver.local.LocalUniResolver.resolveRepresentation(LocalUniResolver.java:64)
universal-resolver-uni-resolver-web-1  | 	at uniresolver.web.WebUniResolver.resolveRepresentation(WebUniResolver.java:50)
universal-resolver-uni-resolver-web-1  | 	at uniresolver.web.servlet.ResolveServlet.doGet(ResolveServlet.java:82)
```

any hints?

**Comment by peacekeeper** [comment]
@fabianekc Your DID `did:oyd:zQmbbgEXLq96rHSRfydhsSQ9HCs6p7Cf4R98Qn7NdXig1Vk%40https%3A%2F%2Fdid2.data-container.net` seems correct with the percent-encoding, so now this looks like a bug in the Universal Resolver. We're looking into it, and I think we'll have a fix soon.

**Comment by peacekeeper** [comment]
@fabianekc I think this should be fixed now with a commit I just pushed: https://github.com/decentralized-identity/universal-resolver/commit/d92c64aa3b9dcac42b2b10e38edb85c4e3879a29

**Comment by BernhardFuchs** [comment]
I've just deployed the new version with the driver and it works with the encoded chars.
@fabianekc Can you pls use the encoded chars in the example DID. Then we can merge it

**Comment by fabianekc** [comment]
@BernhardFuchs the commit `689df40` is actually the change in config.js with the percent encoded examples. Anything else I can do?

**Pull request merged**
