### PR TITLE
Add dom driver (Dominode)

### PR DESCRIPTION
**Pull request by ricjcosme**
This PR adds Dominode's driver-did-dom to the universal resolver and provides support to resolve the `dom` method (as in did:dom:).

Here are some DID resolving examples for the `dom` method:
```
curl -X GET  http://localhost:8080/1.0/identifiers/did:dom:Jjbfgyu7My4RrbRNrXTPBz4PnhnMEE
curl -X GET  http://localhost:8080/1.0/identifiers/did:dom:JkLLdg7ziwV7CvZjtn3jrQNyfk2cim
```

Any questions / comments shoot!

### CODE REVIEW

**Comment by peacekeeper** [comment]
Hello Ricardo, thanks for this! We need some kind of governance process to decide how new methods get added, and we haven't really figured this out yet.

The W3C Credentials Community Group (CCG) is maintaining a registry of "known" DID methods.

I think for now the process should be:
1. Can you join the [W3C Credentials Community Group](https://w3c-ccg.github.io/) and send a message to the mailing list, explaining a bit how the "dom" method works?
1. Do a PR on the [DID method registry](https://w3c-ccg.github.io/did-method-registry/).
1. Do a PR to add the driver to the Universal Resolver [done].
1. (Optional) Provide one or more sample "dom" DIDs for testing?

**Comment by ricjcosme** [comment]
Thanks for the recommendation Markus - I went through the whole process.
Re item 4. here are a couple of DIDs for testing:

- did:dom:2ATjYbDZD4fSTubixW77v5rtaZpjXHxd
- did:dom:2ATjYbDZD4fSTubixW77v5rtaZpjXHxd

**Comment by ricjcosme** [comment]
Can you merge this?

**Comment by peacekeeper** [comment]
Also see https://github.com/w3c-ccg/did-method-registry/pull/4

**Comment by peacekeeper** [comment]
Merged this today and deployed at https://uniresolver.io/. Sorry it took a while.

**Pull request merged**
