### PR TITLE
Add did:tdw driver.

### PR DESCRIPTION
**Pull request by brianorwhatever**
Adds a driver for did:tdw using the [trustdidweb-ts library](https://github.com/decentralized-identity/trustdidweb-ts)

### CODE REVIEW

**Comment by brianorwhatever** [comment]
we are hoping to have this available for IIW next week. I'm concerned I have the same platform issue as the did:btco driver (still on my todo list to fix). Can you please take a look @peacekeeper? Or @kimdhamilton @ankurdotb if you get a chance. Thanks!

**Comment by peacekeeper** [comment]
Thanks @brianorwhatever I think we should be able to get this in before IIW. Could you maybe also add a commit to add this driver to the [README.md](https://github.com/decentralized-identity/universal-resolver/blob/main/README.md) file?

@BernhardFuchs Can you try and deploy this on Monday?

**Comment by BernhardFuchs** [comment]
Hi Brian,  
just tried to deploy the driver but the image is behind a docker login. Pls make it public accessible
```
Error response from daemon: pull access denied for brianrichter/driver-did-tdw, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by brianorwhatever** [comment]
Apologies @BernhardFuchs I had the wrong image name. The correct one is `brianrichter/uni-resolver-driver-did-tdw`. I have updated the code in this PR as well

**Comment by brianorwhatever** [comment]
@peacekeeper added to README as well

**Comment by BernhardFuchs** [comment]
Just tried it with the image `brianrichter/uni-resolver-driver-did-tdw:0.4` and this throws `brianrichter/uni-resolver-driver-did-tdw:0.4` when I do a `docker pull` locally.  
On K8s we get `docker.io/brianrichter/uni-resolver-driver-did-tdw:0.4: not found`

**Comment by brianorwhatever** [comment]
Apologies again @BernhardFuchs 0.4 is now available

**Pull request merged**
