### PR TITLE
Add did:trust driver

### PR DESCRIPTION
**Pull request by bjwswang**

### CODE REVIEW

**Comment by bjwswang** [comment]
docker build failed in this PR 
```
[ERROR] Failed to execute goal on project uni-resolver-core: Could not resolve dependencies for project decentralized-identity:uni-resolver-core:jar:0.2-SNAPSHOT: Failed to collect dependencies at decentralized-identity:did-common-java:jar:0.1.0: Failed to read artifact descriptor for decentralized-identity:did-common-java:jar:0.1.0: Could not transfer artifact decentralized-identity:did-common-java:pom:0.1.0 from/to github-did-common-java (https://maven.pkg.github.com/decentralized-identity/did-common-java): Transfer failed for https://maven.pkg.github.com/decentralized-identity/did-common-java/decentralized-identity/did-common-java/0.1.0/did-common-java-0.1.0.pom 400 Bad Request -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by bjwswang** [comment]
Hi @peacekeeper . Can you help take a look at this issue  ? I alse opened another issue here  https://github.com/decentralized-identity/universal-resolver/issues/111

**Comment by peacekeeper** [comment]
@bjwswang sorry for taking a while to respond.. This should be fixed now, see my comment in https://github.com/decentralized-identity/universal-resolver/issues/111.

**Comment by bjwswang** [comment]
@peacekeeper not a problem. I reopened my pr in https://github.com/decentralized-identity/universal-resolver/pull/120

**Pull request closed without merging**
