### PR TITLE
docs: Add short descriptions of drivers in README.

### PR DESCRIPTION
**Pull request by kilbeggan**
It is impossible for a newbie to understand what the driver refers to. It also helps quickly understand the coverage of supported systems and its nature.

### CODE REVIEW

**Review by peacekeeper — APPROVED** [review]
Hello @kilbeggan thanks for doing this work, I think it's really useful information to be added to the README!

**Comment by peacekeeper** [comment]
@kilbeggan Sorry it looks like there are merge conflicts now.. Could you resolve them? Then we will merge this asap.

**Comment by kilbeggan** [comment]
Sorry, my bad. Looks good for now.

**Comment by peacekeeper** [comment]
Great, thanks again for your contribution!

**Pull request merged**
