### PR TITLE
re enable did:evan driver

### PR DESCRIPTION
**Pull request by S3bb1**
The resolver component was fixed and the test dids should be resolvable again.

Also the resolver component now returns a proper 404 when a wrong did format is passed.

### CODE REVIEW

**Comment by BernhardFuchs** [comment]
Pls also re-add the driver to the [docker-compose](https://github.com/decentralized-identity/universal-resolver/blob/main/docker-compose.yml) file. Otherwise there is no image to deploy.

**Comment by S3bb1** [comment]
Sorry, was missing due to merge conflict. Added it

**Comment by BernhardFuchs** [comment]
The driver doesn't start with following error:
```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by S3bb1** [comment]
Sorry the image was build for ARM64, I rebuild it and pushed it. Can you retry?

**Comment by BernhardFuchs** [comment]
The driver starts now but when resolving the example DID, following error is thrown:
```
yarn run v1.22.18
$ yarn prepare && node dist/index.js
$ tsc
evan.network Resolver driver active on port 8080...
https://testcore.evan.network/did/did:evan:testcore:0x126E901F6F408f5E260d95c62E7c73D9B60fd734
error fetching did document 405 - "Used HTTP Method is not allowed. POST or OPTIONS is required\n"
```

**Pull request merged**
