### PR TITLE
CI/CD config for GitHub and GitLab

### PR DESCRIPTION
**Pull request by philpotisk**
The proposed CI/CD config for GitHub and GitLab will build the Docker image and push it to the Docker Hub registry at _universalresolver/uni-resolver-web:latest_ or to the project-specific GitLab container registry.

This PR also considers to use a default Docker file at 'docker/Dockerfile', in addition to the others in the same folder.

### CODE REVIEW

**Comment by omnecon** [comment]
> @philpotisk It looks like this adds a file `docker/Dockerfile` as a duplicate of `docker/Dockerfile-base-ubuntu`, what's the purpose of that?

@peacekeeper For implementing the build-pipeline for the universal-resolver, I was not sure which of the two base-images I should choose. Thats why I think it would be good to decide on a default-base image and rename this.
Alternatively I can also update the CI/CD scripts with one of the existing Docker-files. In this case, please let me know, which one to use for the universal-resolver.

**Comment by philpotisk** [comment]
> @philpotisk It looks like this adds a file `docker/Dockerfile` as a duplicate of `docker/Dockerfile-base-ubuntu`, what's the purpose of that?

@peacekeeper For implementing the build-pipeline for the universal-resolver, I was not sure which of the two base-images I should choose. Thats why I think it would be good to decide on a default-base image and rename this.
Alternatively I can also update the CI/CD scripts with one of the existing Docker-files. In this case, please let me know, which one to use for the universal-resolver.

**Comment by omnecon** [comment]
@peacekeeper Initially I was using the wrong Docker file, as I just was looking at the docker-folder in the root dir. Instead the right Docker file would have been in: ./resolver/java/uni-resolver-web/docker

With my latest commits, I would suggest to move all Docker-related files to the root folder and remove the folder in ./resolver/java/uni-resolver-web/docker. I guess that having all Docker files in one place makes the project easier to handle.
Anyway, please let me know if you like this approach, or if we should rather stay with the old structure.

**Comment by peacekeeper** [comment]
@omnecon I think I agree that seems to make sense. @philpotisk what do you think?

**Comment by philpotisk** [comment]
@peacekeeper I do agree, since I've made the changes. I just wrote the comment using the wrong GitHub account. Sorry for the confusion!

**Comment by philpotisk** [comment]
As discussed offline, I have reverted the commits regarding the relocation of Docker-files to the root-dir. I further synced up to the master branch, so this PR should be safe to merge back.

**Pull request merged**
