### PR TITLE
feat: update KILT driver to v2

### PR DESCRIPTION
**Pull request by Diiaablo95**
This PR updates the KILT DID driver to v2.1.0 and the DID method specification to v1.0.0

### CODE REVIEW

**Comment by BernhardFuchs** [comment]
There is an issue with one of the test dids.  
`did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5` throws:
```
[invalidDid] Cannot parse DID: did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5
```

**Comment by Diiaablo95** [comment]
@BernhardFuchs thanks for the heads up, it was a slight oversight. I pushed a [fixed version](https://github.com/KILTprotocol/kilt-did-driver/pull/21) of the driver, which now works fine when running standalone, but it still fails when running in the DIF context. The reason is the same: some base64-encoded details might contain the `/` character, which apparently makes resolution fail even before making it to the KILT driver. Is there a way to fix that, perhaps by passing anything that starts with `did:kilt` to the KILT driver, without trying to parse the full URL before?

**Comment by Diiaablo95** [comment]
Here's a log obtained from running a local instance of the DIF resolver

```
uni-resolver-web_1  | [qtp828441346-16] DEBUG servlet.ResolveServlet (doGet) - Incoming resolve request: /1.0/identifiers/did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5
uni-resolver-web_1  | [qtp828441346-16] INFO servlet.ResolveServlet (doGet) - Incoming DID string: did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5
uni-resolver-web_1  | [qtp828441346-16] INFO servlet.ResolveServlet (doGet) - Incoming Accept: header string: */*
uni-resolver-web_1  | [qtp828441346-16] DEBUG servlet.ResolveServlet (doGet) - Using resolution options: {accept=application/did+ld+json}
uni-resolver-web_1  | [qtp828441346-16] DEBUG local.LocalUniResolver (resolveRepresentation) - resolveRepresentation(did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5)  with options: {accept=application/did+ld+json}
uni-resolver-web_1  | [qtp828441346-16] WARN local.LocalUniResolver (resolveOrResolveRepresentation) - Cannot parse DID: did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5
uni-resolver-web_1  | [qtp828441346-16] WARN servlet.ResolveServlet (doGet) - Resolve problem for did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5: Cannot parse DID: did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5
uni-resolver-web_1  | uniresolver.ResolutionException: Cannot parse DID: did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5
uni-resolver-web_1  |   at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentation(LocalUniResolver.java:92)
uni-resolver-web_1  |   at uniresolver.local.LocalUniResolver.resolveRepresentation(LocalUniResolver.java:64)
uni-resolver-web_1  |   at uniresolver.web.WebUniResolver.resolveRepresentation(WebUniResolver.java:50)
uni-resolver-web_1  |   at uniresolver.web.servlet.ResolveServlet.doGet(ResolveServlet.java:82)
uni-resolver-web_1  |   at uniresolver.web.WebUniResolver.handleRequest(WebUniResolver.java:29)
uni-resolver-web_1  |   at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:73)
uni-resolver-web_1  |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
uni-resolver-web_1  |   at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
uni-resolver-web_1  |   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
uni-resolver-web_1  |   at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
uni-resolver-web_1  |   at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
uni-resolver-web_1  |   at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
uni-resolver-web_1  |   at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
uni-resolver-web_1  |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
uni-resolver-web_1  |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
uni-resolver-web_1  |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
uni-resolver-web_1  |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
uni-resolver-web_1  |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
uni-resolver-web_1  |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
uni-resolver-web_1  |   at org.eclipse.jetty.server.Server.handle(Server.java:516)
uni-resolver-web_1  |   at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
uni-resolver-web_1  |   at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
uni-resolver-web_1  |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
uni-resolver-web_1  |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
uni-resolver-web_1  |   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
uni-resolver-web_1  |   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
uni-resolver-web_1  |   at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
uni-resolver-web_1  |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
uni-resolver-web_1  |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
uni-resolver-web_1  |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
uni-resolver-web_1  |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
uni-resolver-web_1  |   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
uni-resolver-web_1  |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
uni-resolver-web_1  |   at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
uni-resolver-web_1  |   at java.base/java.lang.Thread.run(Unknown Source)
uni-resolver-web_1  | [qtp828441346-16] DEBUG result.ResolveRepresentationResult (makeErrorResult) - Created error resolve result: {"didResolutionMetadata":{"error":"invalidDid","errorMessage":"Cannot parse DID: did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5","contentType":"application/did+ld+json"},"didDocumentStream":"","didDocumentMetadata":{}}
uni-resolver-web_1  | [qtp828441346-16] INFO servlet.ResolveServlet (doGet) - Resolve result for did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5: {"didResolutionMetadata":{"error":"invalidDid","errorMessage":"Cannot parse DID: did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5","contentType":"application/did+ld+json"},"didDocumentStream":"","didDocumentMetadata":{}}
uni-resolver-web_1  | [qtp828441346-16] DEBUG util.HttpBindingServerUtil (isMediaTypeAcceptable) - Checking if media type application/ld+json;profile="https://w3id.org/did-resolution" is acceptable for */*: true
uni-resolver-web_1  | [qtp828441346-16] DEBUG servlet.ResolveServlet (doGet) - Supporting HTTP media type */* via content type application/ld+json;profile="https://w3id.org/did-resolution"
uni-resolver-web_1  | [qtp828441346-16] DEBUG util.HttpBindingServerUtil (toHttpBodyResolveRepresentationResult) - Serializing resolve result to HTTP body.
uni-resolver-web_1  | [qtp828441346-16] DEBUG servlet.ServletUtil (sendResponse) - Sending response with status 400 and content type application/ld+json;profile="https://w3id.org/did-resolution" and body (class java.lang.String)
```

**Comment by peacekeeper** [comment]
@Diiaablo95 this is an invalid DID:

`did:kilt:light:014pF5Y2Eo6doQHPLQj5AkndZwtomVB8ab2sRftRS2D9JDdELr:oWFlomlwdWJsaWNLZXlYIBsVppuQ2fi/beBdYf50+n/36FnCjMw+KLSu3AmW9DEGZHR5cGVmeDI1NTE5`

The `/` character is not allowed in the `method-specific-id`, see here: https://www.w3.org/TR/did-core/#did-syntax

Therefore the Universal Resolverr returns an error, before even invoking your driver. If your driver can resolve such DIDs, then it's not spec conformant.

I think the best solution would be to change your DID method to use base64url encoding instead of base64?

**Comment by Diiaablo95** [comment]
Thanks for the clarification @peacekeeper! I'll close this PR for now, work on a fix, and either re-open this or open a new one once we're ready to submit again 😊

**Pull request closed without merging**
