### PR TITLE
DID Universal Resolver Driver

### PR DESCRIPTION
**Pull request by alejandroalffer**
First release of DID driver of AlastriaID MPV2 universal resolver

Thanks for your work, @peacekeeper, and rest of the DIF Team

### CODE REVIEW

**Comment by BernhardFuchs** [comment]
Currently there is an internal network problem within the cluster.  
The reason is that the CI pipeline uses the `docker-compose.yml` file to create the K8s resources. Atm this results in a service `alastria-did-driver-mvp2` but the Resolver looks for `http://alastria-did-driver`. Therefore the driver can't be found by internal DNS.  
To fix this just align the naming.

**Comment by alejandroalffer** [comment]
Done! I didn't realise the name where important. I hope the deployment works now!

**Comment by BernhardFuchs** [comment]
Thx for the quick fix. Everything is fine now.  
We should review the docs and see if we can improve it

**Comment by alejandroalffer** [comment]
Great news have AlastraID in this DIF project!

**Comment by peacekeeper** [comment]
Yes this is very exciting, thanks @alejandroalffer for your contribution!

**Pull request merged**
