### PR TITLE
feat: Bump Cheqd Resolver version

### PR DESCRIPTION
**Pull request by Toktar**

### CODE REVIEW

**Comment by peacekeeper** [comment]
Hello @Toktar as we discussed, I think you may also want to change the line here:
https://github.com/decentralized-identity/universal-resolver/blob/main/uni-resolver-web/src/main/resources/application.yml#L239

Otherwise, with the current configuration, the Universal Resolver will not actually use your driver Docker container, but instead just use your remote HTTP endpoint.

Or do you see this differently?

**Comment by peacekeeper** [comment]
To be specific, you could replace `https://resolver.cheqd.net/` with `http://cheqd-did-driver:1313/` on that line in application.yml.

**Comment by Toktar** [comment]
Hello @peacekeeper ,
Thank you for the fast response. I suggest leaving the use of the remote driver.
And leave the indication of the container and its version in case a client wants to run their (trusted) Cheqd driver locally, for specific cases like DID resources.
What do you think?

**Comment by peacekeeper** [comment]
@Toktar That's also fine, I agree we can leave it like this!

In the past we have had many discussions about pros/cons of local drivers vs. remote drivers, but right now we have a mix of both, so this is totally fine.

**Pull request merged**
