### PR TITLE
add quarkid to the universal resolver 

### PR DESCRIPTION
**Pull request by toescudero**

### CODE REVIEW

**Comment by BernhardFuchs** [comment]
Just tested the driver and it throws following error when resolving the example DID:
```
Resolving did:quarkid:EiA9SoiWkqduxPJcVk3UVoUGWm3WL2S6mox3qH3AWVCwMQ
Error fetching DID log: 56 | export const clone = (input: any) => JSON.parse(JSON.stringify(input));
57 |
58 | export const getBaseUrl = (id: string) => {
59 |   const parts = id.split(':');
60 |   if (!id.startsWith('did:tdw:') || parts.length < 4) {
61 |     throw new Error(`${id} is not a valid did:tdw identifier`);
               ^
error: did:quarkid:EiA9SoiWkqduxPJcVk3UVoUGWm3WL2S6mox3qH3AWVCwMQ is not a valid did:tdw identifier
      at getBaseUrl (/usr/src/app/node_modules/trustdidweb-ts/src/utils.ts:61:11)
      at getFileUrl (/usr/src/app/node_modules/trustdidweb-ts/src/utils.ts:72:19)
      at /usr/src/app/node_modules/trustdidweb-ts/src/utils.ts:82:17
      at fetchLogFromIdentifier (/usr/src/app/node_modules/trustdidweb-ts/src/utils.ts:80:46)
      at /usr/src/app/node_modules/trustdidweb-ts/src/method.ts:76:21
      at resolveDID (/usr/src/app/node_modules/trustdidweb-ts/src/method.ts:70:34)
      at /usr/src/app/index.ts:10:33
      at /usr/src/app/index.ts:7:40
      at handle (50:32)
```

**Comment by toescudero** [comment]
sorry for that , miss a config in the web resolver

**Comment by BernhardFuchs** [comment]
Just tried it and the driver and the `universal-resolver` throws following error:
```
2024-11-11T08:18:59,570 WARN  [qtp840737335-18] u.w.s.ResolveServlet: Resolve problem for did:quarkid:EiA9SoiWkqduxPJcVk3UVoUGWm3WL2S6mox3qH3AWVCwMQ: 404 Not Found ({"statusCode":404,"message":"Cannot GET /1.0/identifiers/did:quarkid:EiA9SoiWkqduxPJcVk3UVoUGWm3WL2S6mox3qH3AWVCwMQ","error":"Not Found"})
uniresolver.ResolutionException: 404 Not Found ({"statusCode":404,"message":"Cannot GET /1.0/identifiers/did:quarkid:EiA9SoiWkqduxPJcVk3UVoUGWm3WL2S6mox3qH3AWVCwMQ","error":"Not Found"})
	at uniresolver.driver.http.HttpDriver.resolveRepresentation(HttpDriver.java:151)
	at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentationWithDrivers(LocalUniResolver.java:173)
	at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentation(LocalUniResolver.java:126)
	at uniresolver.local.LocalUniResolver.resolveRepresentation(LocalUniResolver.java:73)
	at uniresolver.local.LocalUniResolver.resolveRepresentation(LocalUniResolver.java:68)
	at uniresolver.web.WebUniResolver.resolveRepresentation(WebUniResolver.java:56)
	at uniresolver.web.servlet.ResolveServlet.doGet(ResolveServlet.java:92)
```

Does that work for you locally?

**Comment by toescudero** [comment]
sory the public image was old . now if you delete the container and pull the latest it should work

**Pull request merged**
