### PR TITLE
chore: add orb did driver

### PR DESCRIPTION
**Pull request by fqutishat**
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>

### CODE REVIEW

**Comment by BernhardFuchs** [comment]
The container doesn't start and logs following:
```
Usage:
  rp [flags]
  rp [command]

Available Commands:
  help        Help about any command
  start       Start orb driver

Flags:
  -h, --help   help for rp

Use "rp [command] --help" for more information about a command.
```
Seems to be a wrong command invocation.

**Comment by fqutishat** [comment]
> The container doesn't start and logs following:
> 
> ```
> Usage:
>   rp [flags]
>   rp [command]
> 
> Available Commands:
>   help        Help about any command
>   start       Start orb driver
> 
> Flags:
>   -h, --help   help for rp
> 
> Use "rp [command] --help" for more information about a command.
> ```
> 
> Seems to be a wrong command invocation.

@BernhardFuchs you need command start https://github.com/decentralized-identity/universal-resolver/pull/221/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R211

**Comment by fqutishat** [comment]
@BernhardFuchs test it locally too this logs for orb driver
```
 [httpserver] 2021/07/09 11:50:52 UTC - httpserver.New -> INFO Registering handler for [/resolveDID]
 [orb-driver] 2021/07/09 11:50:52 UTC - startcmd.(*HTTPServer).Start -> INFO started orb driver service
 [httpserver] 2021/07/09 11:50:52 UTC - httpserver.(*Server).Start.func1 -> INFO listening for requests on [0.0.0.0:8121]
```

**Comment by BernhardFuchs** [comment]
@fqutishat Pls provide full command to run the container. Can't make it work locally or on kubernetes.

**Comment by fqutishat** [comment]
> @fqutishat Pls provide full command to run the container. Can't make it work locally or on kubernetes.

the command is just start

**Comment by BernhardFuchs** [comment]
@fqutishat I pulled the image from `ghcr.io/trustbloc-cicd/orb-did-driver:v0.1.0-snapshot-894f273` but don't know how to start the container. Pls provide full `docker run` command.

**Comment by fqutishat** [comment]
> @fqutishat I pulled the image from `ghcr.io/trustbloc-cicd/orb-did-driver:v0.1.0-snapshot-894f273` but don't know how to start the container. Pls provide full `docker run` command.

```
docker run  ghcr.io/trustbloc/orb-did-driver:v0.1.2 start --host-url=0.0.0.0:8121
```

**Comment by BernhardFuchs** [comment]
Ok, thx. I can run it locally with docker now.  
There is still an issue when deploying to kubernetes. The command `start` or `orb-method start` or, like the trustbloc-driver, `sh -c did-method start` are not found in the `PATH` when I pass it to the container.

**Comment by fqutishat** [comment]
> Ok, thx. I can run it locally with docker now.
> There is still an issue when deploying to kubernetes. The command `start` or `orb-method start` or, like the trustbloc-driver, `sh -c did-method start` are not found in the `PATH` when I pass it to the container.

@BernhardFuchs example for kubernetes https://github.com/trustbloc/k8s/blob/main/orb-driver/kustomize/orb-driver/base/deployment.yml#L28

**Comment by BernhardFuchs** [comment]
Thx, the driver is running now with following startup logs:
```
 [httpserver] 2021/07/09 14:38:51 UTC - httpserver.New -> INFO Registering handler for [/resolveDID]
 [orb-driver] 2021/07/09 14:38:51 UTC - startcmd.(*HTTPServer).Start -> INFO started orb driver service
 [httpserver] 2021/07/09 14:38:51 UTC - httpserver.(*Server).Start.func1 -> INFO listening for requests on [0.0.0.0:8121]
```

When I try to resolve the example did, it throws following error:
```
[internalError] Driver cannot retrieve result for did:orb:ipfs:bafkreifco5fp7ztvqnnvv4aqnnbktuvzhlh5tofr65ahyy37euafoscn7m:EiClaNSwhKSP6tQe36bYc5w41oRpCi1xv89MkUnNBm8agw: 400 Bad Request (failed to resolve did: failed to get endpoints: getting endpointAnchorOrigin from cache: fetching cacheable object: unable to read CID[bafkreifco5fp7ztvqnnvv4aqnnbktuvzhlh5tofr65ahyy37euafoscn7m] from CAS: failed to send request: Get "https://ipfs.io/ipfs/bafkreifco5fp7ztvqnnvv4aqnnbktuvzhlh5tofr65ahyy37euafoscn7m": x509: certificate signed by unknown authority)
```

The env variable `ORB_DRIVER_HOST_URL` is set to `0.0.0.0:8121`

**Comment by fqutishat** [comment]
> Thx, the driver is running now with following startup logs:
> 
> ```
>  [httpserver] 2021/07/09 14:38:51 UTC - httpserver.New -> INFO Registering handler for [/resolveDID]
>  [orb-driver] 2021/07/09 14:38:51 UTC - startcmd.(*HTTPServer).Start -> INFO started orb driver service
>  [httpserver] 2021/07/09 14:38:51 UTC - httpserver.(*Server).Start.func1 -> INFO listening for requests on [0.0.0.0:8121]
> ```
> 
> When I try to resolve the example did, it throws following error:
> 
> ```
> [internalError] Driver cannot retrieve result for did:orb:ipfs:bafkreifco5fp7ztvqnnvv4aqnnbktuvzhlh5tofr65ahyy37euafoscn7m:EiClaNSwhKSP6tQe36bYc5w41oRpCi1xv89MkUnNBm8agw: 400 Bad Request (failed to resolve did: failed to get endpoints: getting endpointAnchorOrigin from cache: fetching cacheable object: unable to read CID[bafkreifco5fp7ztvqnnvv4aqnnbktuvzhlh5tofr65ahyy37euafoscn7m] from CAS: failed to send request: Get "https://ipfs.io/ipfs/bafkreifco5fp7ztvqnnvv4aqnnbktuvzhlh5tofr65ahyy37euafoscn7m": x509: certificate signed by unknown authority)
> ```
> 
> The env variable `ORB_DRIVER_HOST_URL` is set to `0.0.0.0:8121`

you need to add --tls-systemcertpool=true
like this
```
docker run  ghcr.io/trustbloc/orb-did-driver:v0.1.2 start --host-url=0.0.0.0:8121 --tls-systemcertpool=true
```

**Comment by BernhardFuchs** [comment]
Ok thx, it works now.  
I had to change the CI pipeline and will merge the driver with this PR https://github.com/decentralized-identity/universal-resolver/pull/223

**Pull request closed without merging**
