### PR TITLE
fix(deps): update drivers, tests and examples for did:ethr and did:web

### LINKED ISSUE #168: Update did web driver to support pathname based dids
See: https://github.com/w3c-ccg/did-method-web/issues/24

We should be able to resolver pathname based did webs, with the universal resolver

### PR DESCRIPTION
**Pull request by mirceanis**
Using driver version 2.0.8 which updates both resolvers to did resolution result

Features:
* update did:ethr resolver to the most recent version that is did-core-spec compliant and also provides a valid JSON-LD `@context`
* update did:web resolver to support DIDDocuments with `verificationMethod` (see `did:web:did.actor:mike`)
* did:web resolver now also supports `%` encoding for `host:port` and path components (see https://github.com/w3c-ccg/did-method-web/issues/7)

closes #168
closes https://github.com/w3c-ccg/did-method-web/issues/24

### CODE REVIEW

**Comment by mirceanis** [comment]
sorry, ignore this for now. it has a bug

**Comment by AlexYenkalov** [comment]
@mirceanis it seems that there is still a bug

curl -X GET http://localhost:8081/1.0/identifiers/did:ethr:0x1e:0x02b97c30de767f084ce3080168ee293053ba33b235d7116a3263d29f1450936b71

Cannot read property 'blockTag' of undefined

**Comment by mirceanis** [comment]
@AlexYenkalov thank you for your vigilance. I will take another look.

**Comment by mirceanis** [comment]
@AlexYenkalov I tested again on 2 different machines and didn't see any error.
What setup are you using in your tests?

**Comment by peacekeeper** [comment]
Thanks for working on updating this driver! Let us know when you think it's ready to merge..

**Comment by mirceanis** [comment]
I think it's ready now, but I marked it as draft because @AlexYenkalov ran into some issues.
I don't see issues on my end so I'm still trying to reproduce.

**Comment by cihanss** [comment]
I've also tested it. I didn't encounter any issue with resolving DIDs, including [the one](http://localhost:8081/1.0/identifiers/did:ethr:0x1e:0x02b97c30de767f084ce3080168ee293053ba33b235d7116a3263d29f1450936b71) @AlexYenkalov refers to.

**Pull request merged**
